[flatris_app]
flatris-app ansible_host={{ lookup('env', 'FLATRIS_APP_IP') }}

[flatris_app:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/flatris-keypair.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3